"""add_affiliates_products_orders

Revision ID: 1a460bf62676
Revises: d493a9415f96
Create Date: 2026-02-15 20:02:25.143159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a460bf62676'
down_revision: Union[str, None] = 'd493a9415f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('price_public', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_distributor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('pv', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('bv', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('is_kit', sa.Boolean(), nullable=False),
    sa.Column('kit_tier', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('country_availability', postgresql.ARRAY(sa.String(length=2)), server_default='{SV}', nullable=False),
    sa.Column('track_stock', sa.Boolean(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kit_tier IN ('ESP1', 'ESP2', 'ESP3')", name='chk_product_kit_tier'),
    sa.CheckConstraint("status IN ('active', 'inactive', 'discontinued')", name='chk_product_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sku', name='uq_products_tenant_sku')
    )
    op.create_index(op.f('ix_products_is_kit'), 'products', ['is_kit'], unique=False)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_table('affiliates',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('affiliate_code', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('id_doc_type', sa.String(length=20), nullable=True),
    sa.Column('id_doc_number', sa.String(length=50), nullable=True),
    sa.Column('tax_id_type', sa.String(length=20), nullable=True),
    sa.Column('tax_id_number', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('sponsor_id', sa.UUID(), nullable=True),
    sa.Column('placement_parent_id', sa.UUID(), nullable=True),
    sa.Column('placement_side', sa.String(length=5), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('kit_tier', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_rank', sa.String(length=30), nullable=False),
    sa.Column('highest_rank', sa.String(length=30), nullable=False),
    sa.Column('pv_current_period', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bv_left_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bv_right_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bv_left_carry', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bv_right_carry', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kit_tier IN ('ESP1', 'ESP2', 'ESP3')", name='chk_kit_tier'),
    sa.CheckConstraint("placement_side IN ('left', 'right')", name='chk_placement_side'),
    sa.CheckConstraint("status IN ('pending', 'active', 'inactive', 'suspended', 'cancelled')", name='chk_affiliate_status'),
    sa.CheckConstraint('placement_parent_id IS DISTINCT FROM id', name='chk_no_self_placement'),
    sa.CheckConstraint('sponsor_id IS DISTINCT FROM id', name='chk_no_self_sponsor'),
    sa.ForeignKeyConstraint(['placement_parent_id'], ['affiliates.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['affiliates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'affiliate_code', name='uq_affiliates_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_affiliates_tenant_email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_affiliates_affiliate_code'), 'affiliates', ['affiliate_code'], unique=True)
    op.create_index(op.f('ix_affiliates_sponsor_id'), 'affiliates', ['sponsor_id'], unique=False)
    op.create_index(op.f('ix_affiliates_status'), 'affiliates', ['status'], unique=False)
    op.create_index(op.f('ix_affiliates_tenant_id'), 'affiliates', ['tenant_id'], unique=False)
    op.create_table('orders',
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('affiliate_id', sa.UUID(), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_pv', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_bv', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("order_type IN ('enrollment', 'repurchase', 'autoship', 'admin')", name='chk_order_type'),
    sa.CheckConstraint("status IN ('pending_payment', 'paid', 'in_preparation', 'shipped', 'delivered', 'cancelled', 'returned')", name='chk_order_status'),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index(op.f('ix_orders_affiliate_id'), 'orders', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pv', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('bv', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_pv', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_bv', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_order_items_tenant_id'), 'order_items', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_tenant_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_affiliate_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_affiliates_tenant_id'), table_name='affiliates')
    op.drop_index(op.f('ix_affiliates_status'), table_name='affiliates')
    op.drop_index(op.f('ix_affiliates_sponsor_id'), table_name='affiliates')
    op.drop_index(op.f('ix_affiliates_affiliate_code'), table_name='affiliates')
    op.drop_table('affiliates')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_is_kit'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
